### ISSUE TITLE
[请求添加] 实体清理的黑名单配置

### ISSUE THREAD

**Issue by EnterFor** [ScottCTD/ScottsEssential#2]
默认的白名单配置只有几种，如果加了些其他Mod有很多实体要需要加白名单。
如果加了黑名单配置，只需要设置需要清理的实体，其他的不清理！
虽然不影响整体使用，如果能加入最好啦！ღ( ´･ᴗ･` )比心

**Comment by ScottCTD** [comment]
收到

**Comment by ScottCTD** [comment]
Fixed in 71558f65
