### ISSUE TITLE
1.0.5版本下 /hat 会直接覆盖掉头上的东西

### ISSUE THREAD

**Issue by Brian01071** [ScottCTD/ScottsEssential#4]
1.0.5版本下 /hat会直接覆盖掉头上的东西

**Comment by scottctd** [comment]
很抱歉因为我的疏忽为您带来困扰，已在 56a3eaf 修复

**Comment by Brian01071** [comment]
什么时候会释出新版嘞～，支持1.16.4吗

**Comment by scottctd** [comment]
支持的，我可以先给你个修复bug的预览版

https://cloud.189.cn/t/zQJ3Iz7fUBj2

**Comment by Brian01071** [comment]
好的，十分感谢~
